language: go
sudo: false

go:
  - 1.20.x

install:
  - go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.29.1
  - curl -L https://github.com/protocolbuffers/protobuf/releases/download/v22.2/protoc-22.2-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d "$HOME"/protoc
  - mkdir -p "$HOME"/src && ln -s "$HOME"/protoc "$HOME"/src/protobuf

env:
  - PATH=$HOME/protoc/bin:$PATH

script:
  - make
  - make test
